### ISSUE TITLE
postgres patroni pgbackrest docker

### ISSUE THREAD

**Issue by haminhcong** [haminhcong/blog-v2#1]
```
bash-4.4$ patronictl show-config hippo-ha
loop_wait: 10
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=db archive-push "%p"
    archive_mode: 'on'
    archive_timeout: 60s
    jit: 'off'
    password_encryption: scram-sha-256
    restore_command: pgbackrest --stanza=db archive-get %f "%p"
    shared_preload_libraries: pgaudit
    ssl: 'on'
    ssl_ca_file: /pgconf/tls/ca.crt
    ssl_cert_file: /pgconf/tls/tls.crt
    ssl_key_file: /pgconf/tls/tls.key
    unix_socket_directories: /tmp/postgres
    wal_level: logical
  pg_hba:
  - local all "postgres" peer
  - hostssl replication "_crunchyrepl" all cert
  - hostssl "postgres" "_crunchyrepl" all cert
  - host all "_crunchyrepl" all reject
  - hostssl all all all md5
  use_pg_rewind: true
  use_slots: false
ttl: 30
```
